### ISSUE TITLE
"Timing": how about "Clock"? or "SharedClock"?

### ISSUE THREAD

**Issue by dontcallmedom** [webtiming/timingobject#1]
"Timing" feels a bit weird as a name of an interface; I suggest we use a more descriptive name, e.g. Clock or SharedClock

**Comment by ingararntzen** [comment]
If we name the object by what it "is", "clock" is a bit limiting, "stop-watch" is more correct, and "motion" is even more precise. However, all these names have unwanted effects when it comes to indicating purpose. "Clock" for example hints of something that is read-only, the traditional use-case for a stop-watch is only to measure time, whereas "motion" is an unfamiliar concept and does not imply any usage. For these reasons we opted rather to name the object after its main purpose which is "timing/ temporal control". "TimingControllerObject" would perhaps be more correct than simply "TimingObject", but it is also a bit more clunky. I hope "TimingObject" is an acceptable compromise.

**Comment by ingararntzen** [comment]
I think we may close this one now. I've also added a subsection in the introduction in the spec indicating the rational for the name.
