### ISSUE TITLE
State Vector Attributes

### ISSUE THREAD

**Issue by ingararntzen** [webtiming/timingobject#6]
The state vector attributes are full names
vector.position vector.velocity, vector.acceleration, vector.timestamp

These long names are very unpractical as these properties are used frequently.
I would like to see them shortened
vector.pos, vector.vel, vector.acc, vector.ts
or
vector.p, vector.v or vector.a, vector.t

I've used array indices before (vector[0], vector[1], vector[2], vector[3] ), but I suppose letters are far more readable

**Comment by Snarkdoof** [comment]
I support shorter names, pos, vel, acc and ts is more to my liking due to a
nice tradeoff between compact and readability.

**Comment by dontcallmedom** [comment]
in general, short names are left as an exercise to the IDEs or to libraries; they otherwise hinder readability and discoverability.

Another way to look at it is that there a lot more people that will need to read a given piece of code than there are people that will need to write it :)
